trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TerraformSecrets

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Terraform
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'
            displayName: 'Install Terraform'

          - script: |
              cd terraform
              terraform init
            displayName: 'Terraform Init'

          - script: |
              cd terraform
              terraform apply -auto-approve
            displayName: 'Terraform Apply'

  - stage: DeployMagento
    dependsOn: DeployInfrastructure
    jobs:
      - job: AKS_Deployment
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure'  # Replace with your Azure service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group magento-rg --name magento-cluster
                helm repo add bitnami https://charts.bitnami.com/bitnami
                helm repo update
                helm install magento bitnami/magento -f helm/magento-values.yaml
            displayName: 'Deploy Magento on AKS'

