trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TerraformSecrets

stages:
  - stage: DeployInfrastructure
    displayName: 'Terraform Provisioning'
    jobs:
      - job: Terraform
        displayName: 'Terraform Init & Apply'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'
            displayName: 'Install Terraform'

          - script: |
              cd terraform
              terraform init
            displayName: 'Terraform Init'

          - script: |
              cd terraform
              terraform apply -auto-approve \
                -var "subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                -var "client_id=$(ARM_CLIENT_ID)" \
                -var "client_secret=$(ARM_CLIENT_SECRET)" \
                -var "tenant_id=$(ARM_TENANT_ID)"
            displayName: 'Terraform Apply'

  - stage: DeployMagento
    displayName: 'Deploy Magento on AKS'
    dependsOn: DeployInfrastructure
    jobs:
      - job: AKSDeployment
        displayName: 'Helm Install Magento'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure'  # Replace with your Azure service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group magento-rg --name magento-cluster
                helm repo add bitnami https://charts.bitnami.com/bitnami
                helm repo update
                helm install magento bitnami/magento -f helm/magento-values.yaml
            displayName: 'Install Magento on AKS'

