trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TerraformSecrets

stages:
  - stage: TerraformProvisioning
    displayName: 'Provision Infrastructure with Terraform'
    jobs:
      - job: TerraformJob
        displayName: 'Initialize & Apply Terraform'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.6.6'
            displayName: 'Install Terraform'

          - script: |
              cd terraform
              terraform init
            displayName: 'Terraform Init'

          - script: |
              cd terraform
              terraform apply -auto-approve \
                -var "subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                -var "client_id=$(ARM_CLIENT_ID)" \
                -var "client_secret=$(ARM_CLIENT_SECRET)" \
                -var "tenant_id=$(ARM_TENANT_ID)"
            displayName: 'Terraform Apply Infrastructure'

  - stage: DeployMagentoAKS
    displayName: 'Deploy Magento on AKS with Helm'
    dependsOn: TerraformProvisioning
    jobs:
      - job: MagentoHelmJob
        displayName: 'Install Magento via Helm on AKS'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure'  # 🔁 Replace with your service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging into AKS cluster..."
                az aks get-credentials --resource-group magento-rg --name magento-cluster

                echo "Adding Bitnami Helm repo..."
                helm repo add bitnami https://charts.bitnami.com/bitnami
                helm repo update

                echo "Installing Magento chart..."
                helm install magento bitnami/magento -f helm/magento-values.yaml
            displayName: 'Deploy Magento Helm Chart'

