trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: TerraformSecrets

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.6.6'
    displayName: 'Install Terraform'

  - script: |
      echo "##[group]Terraform Init"
      cd terraform
      terraform init -backend=true
      echo "##[endgroup]"
    displayName: 'Terraform Init'

  - script: |
      echo "##[group]Terraform Plan"
      cd terraform
      terraform plan -out=tfplan
      echo "##[endgroup]"
    displayName: 'Terraform Plan'

  - script: |
      echo "##[group]Terraform Apply"
      cd terraform
      terraform apply -auto-approve tfplan
      echo "##[endgroup]"
    displayName: 'Terraform Apply'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure'  # 👈 Replace with your service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Assigning role to new SP..."

        SP_ID=$(az ad sp list --display-name "my-sp-name" --query "[0].objectId" -o tsv)
        SCOPE="/subscriptions/$(az account show --query id -o tsv)"

        az role assignment create \
          --assignee-object-id $SP_ID \
          --role "Owner" \
          --scope $SCOPE
      displayName: 'Assign Role to Service Principal (Owner)'

