trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TerraformSecrets

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.6.6'
    displayName: 'Install Terraform'

  - script: |
      cd terraform
      terraform init
    displayName: 'Terraform Init'

  - script: |
      cd terraform
      terraform apply -auto-approve
    displayName: 'Terraform Apply'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials --resource-group magento-rg --name magento-cluster
    displayName: 'Get AKS Credentials'

  - script: |
      helm repo add bitnami https://charts.bitnami.com/bitnami
      helm repo update
      helm install magento bitnami/magento -f helm/magento-values.yaml
    displayName: 'Deploy Magento via Helm'

